name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: silvertakana/worldwideview/.github/workflows/shared-docker.yml@ci/infra-overhaul
    with:
      tags: |
        type=raw,value=latest
        type=sha,prefix=sha-
    secrets: inherit

  build-ci:
    uses: silvertakana/worldwideview/.github/workflows/shared-docker.yml@ci/infra-overhaul
    with:
      tags: type=raw,value=ci
      smoke-test-path: /
    secrets: inherit
